function R = z2R_TwoLinkArm(in1,in2)
%Z2R_TWOLINKARM
%    R = Z2R_TWOLINKARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    23-Oct-2013 01:04:35

l = in2(1,:);
th1 = in1(1,:);
th2 = in1(3,:);
t2 = cos(th1);
t3 = l.*t2;
t4 = sin(th1);
t5 = l.*t4;
R = [zeros(1,length(t2));zeros(1,length(t2));t3;t5;t3+l.*cos(th2);t5+l.*sin(th2)];
