function A = A_jumping_leg(in1,in2)
%A_JUMPING_LEG
%    A = A_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:50

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(2,:);
c2 = in2(3,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = c1.^2;
t7 = c2.^2;
t8 = l.^2;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t13 = c1.*m1.*t2;
t14 = c2.*m2.*t3;
t15 = l.*m2.*t2;
t16 = l.*mh.*t2;
t17 = l.*mh.*t3;
t18 = c2.*l.*t2.*t3.*2.0;
t19 = c2.*l.*t4.*t5.*2.0;
t22 = t2.*t3.*t8.*2.0;
t23 = t4.*t5.*t8.*2.0;
t20 = t8.*t9.*2.0;
t21 = t8.*t11.*2.0;
t24 = t14+t17;
t25 = t13+t15+t16;
t26 = t18+t19;
t28 = t22+t23;
t27 = t20+t21;
t29 = (m2.*t26)./2.0;
t30 = (mh.*t28)./2.0;
t31 = t29+t30;
A = reshape([m1+m2+mh,t25,t24,t25,I1+(m2.*t27)./2.0+(mh.*t27)./2.0+(m1.*(t6.*t9.*2.0+t6.*t11.*2.0))./2.0,t31,t24,t31,I2+(m2.*(t7.*t10.*2.0+t7.*t12.*2.0))./2.0+(mh.*(t8.*t10.*2.0+t8.*t12.*2.0))./2.0],[3,3]);
