function b = b_jumping_leg(in1,in2,Fy,in4)
%B_JUMPING_LEG
%    B = B_JUMPING_LEG(IN1,IN2,FY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:50

c1 = in4(2,:);
c2 = in4(3,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in4(9,:);
l = in4(1,:);
m1 = in4(4,:);
m2 = in4(5,:);
mh = in4(6,:);
tau1 = in2(:,1);
tau2 = in2(:,2);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = c1.^2;
t7 = l.^2;
t8 = dth1.*l.*t2;
t9 = dth2.*l.*t3;
t10 = c2.*dth2.*t5;
t11 = dth1.*l.*t4;
t12 = dth2.*l.*t5;
t13 = c1.*dth1.*t2;
t14 = c2.*dth2.*t3;
t15 = dy+t13;
t16 = t10+t11;
t17 = t11+t12;
t18 = dy+t8+t14;
t19 = dy+t8+t9;
mt1 = [Fy-g.*m1-g.*m2-g.*mh+dth2.*(m2.*t10+mh.*t12)+dth1.*(m2.*t11+mh.*t11+c1.*dth1.*m1.*t4)];
mt2 = [tau1-tau2+dth2.*((mh.*(dth2.*t2.*t5.*t7.*2.0-dth2.*t3.*t4.*t7.*2.0))./2.0-(m2.*(c2.*t4.*t9.*2.0-l.*t2.*t10.*2.0))./2.0)-dth1.*((m2.*(l.*t2.*t16.*2.0-l.*t4.*t18.*2.0))./2.0+(mh.*(l.*t2.*t17.*2.0-l.*t4.*t19.*2.0))./2.0-(m1.*(c1.*t4.*t15.*2.0-dth1.*t2.*t4.*t6.*2.0))./2.0)-(m1.*(c1.*dth1.*t4.*t15.*2.0-dth1.^2.*t2.*t4.*t6.*2.0))./2.0+(m2.*(t8.*t16.*2.0-t11.*t18.*2.0))./2.0+(mh.*(t8.*t17.*2.0-t11.*t19.*2.0))./2.0-c1.*g.*m1.*t2-g.*l.*m2.*t2-g.*l.*mh.*t2];
mt3 = [tau2-dth1.*((mh.*(dth1.*t2.*t5.*t7.*2.0-dth1.*t3.*t4.*t7.*2.0))./2.0+(m2.*(c2.*t5.*t8.*2.0-c2.*t3.*t11.*2.0))./2.0)-dth2.*((m2.*(c2.*t3.*t16.*2.0-c2.*t5.*t18.*2.0))./2.0+(mh.*(l.*t3.*t17.*2.0-l.*t5.*t19.*2.0))./2.0)-(m2.*(t10.*t18.*2.0-t14.*t16.*2.0))./2.0+(mh.*(t9.*t17.*2.0-t12.*t19.*2.0))./2.0-c2.*g.*m2.*t3-g.*l.*mh.*t3];
b = reshape([mt1,mt2,mt3],3,1);
