function C = C_jumping_leg(in1,in2,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:51

y = in1(1,:);
C = y;
