function COM = COM_jumping_leg(in1,in2)
%COM_JUMPING_LEG
%    COM = COM_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Nov-2021 02:45:07

c1 = in2(2,:);
c2 = in2(3,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t6 = m1+m2+mh;
t5 = l.*t2;
t7 = cos(t4);
t8 = l.*t3;
t9 = sin(t4);
t10 = c1.*m1.*t2;
t15 = 1.0./t6;
t11 = c2.*t7;
t12 = l.*t7;
t13 = c2.*t9;
t14 = l.*t9;
t16 = t5+t11;
t17 = t5+t12;
t18 = m2.*t16;
t19 = mh.*t17;
t20 = t10+t18+t19;
COM = [t15.*t20;t15.*(m2.*(t8+t13+y)+mh.*(t8+t14+y)+m1.*(y+c1.*t3));-dth2.*t15.*(m2.*t13+mh.*t14)-dth1.*t15.*(m2.*(t8+t13)+mh.*(t8+t14)+c1.*m1.*t3);dy+dth2.*t15.*(m2.*t11+mh.*t12)+dth1.*t15.*t20];
