function COM = COM_jumping_leg(in1,in2)
%COM_JUMPING_LEG
%    COM = COM_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:51

c1 = in2(2,:);
c2 = in2(3,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t7 = m1+m2+mh;
t6 = l.*t2;
t8 = l.*t4;
t9 = c1.*m1.*t2;
t10 = 1.0./t7;
COM = [t10.*(t9+m2.*(t6+c2.*t3)+mh.*(t6+l.*t3));t10.*(m2.*(t8+y+c2.*t5)+mh.*(t8+y+l.*t5)+m1.*(y+c1.*t4));-dth1.*t10.*(m2.*t8+mh.*t8+c1.*m1.*t4)-dth2.*t10.*(c2.*m2.*t5+l.*mh.*t5);dy+dth1.*t10.*(t9+m2.*t6+mh.*t6)+dth2.*t10.*(c2.*m2.*t3+l.*mh.*t3)];
