function dC = dC_jumping_leg(in1,in2,in3)
%DC_JUMPING_LEG
%    DC = DC_JUMPING_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:51

dy = in1(4,:);
dC = dy;
