function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:50

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(2,:);
c2 = in2(3,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in2(9,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = dth1.^2;
t7 = l.*t4;
t8 = dth1.*l.*t2;
t9 = dth1.*t7;
E = (I1.*t6)./2.0+(m2.*((dy+t8+c2.*dth2.*t3).^2+(t9+c2.*dth2.*t5).^2))./2.0+(mh.*((dy+t8+dth2.*l.*t3).^2+(t9+dth2.*l.*t5).^2))./2.0+(m1.*((dy+c1.*dth1.*t2).^2+c1.^2.*t4.^2.*t6))./2.0+(I2.*dth2.^2)./2.0+g.*m1.*(y+c1.*t4)+g.*m2.*(t7+y+c2.*t5)+g.*mh.*(t7+y+l.*t5);
