function keypoints = keypoints_jumping_leg(in1,in2)
%KEYPOINTS_JUMPING_LEG
%    KEYPOINTS = KEYPOINTS_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Nov-2021 02:45:06

l = in2(1,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l.*t2;
t6 = l.*t3;
keypoints = reshape([t5+l.*cos(t4),t6+y+l.*sin(t4),0.0,t5,t6+y,0.0,0.0,y,0.0],[3,3]);
