function keypoints = keypoints_jumping_leg(in1,in2)
%KEYPOINTS_JUMPING_LEG
%    KEYPOINTS = KEYPOINTS_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Nov-2021 13:10:51

l = in2(1,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = l.*t2;
t5 = l.*t3;
keypoints = reshape([t4+l.*cos(th2),t5+y+l.*sin(th2),0.0,t4,t5+y,0.0,0.0,y,0.0],[3,3]);
