function C = C_jumping_leg(in1,in2,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2021 14:19:37

y = in1(1,:);
C = y;
