function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2021 14:19:36

I1 = in2(8,:);
I2 = in2(9,:);
c1 = in2(3,:);
c2 = in2(4,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in2(10,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(5,:);
m2 = in2(6,:);
mh = in2(7,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = dth1.^2;
t6 = l1.*t2;
t7 = cos(t4);
t8 = l1.*t3;
t9 = sin(t4);
t10 = c2.*t9;
t11 = l2.*t9;
E = (I1.*t5)./2.0+(m1.*((dy+c1.*dth1.*t2).^2+c1.^2.*t3.^2.*t5))./2.0+(I2.*dth2.^2)./2.0+(m2.*((dth1.*(t8+t10)+dth2.*t10).^2+(dy+dth1.*(t6+c2.*t7)+c2.*dth2.*t7).^2))./2.0+(mh.*((dth1.*(t8+t11)+dth2.*t11).^2+(dy+dth1.*(t6+l2.*t7)+dth2.*l2.*t7).^2))./2.0+g.*m1.*(y+c1.*t3)+g.*m2.*(t8+t10+y)+g.*mh.*(t8+t11+y);
