function E = energy_TwoLinkArm(in1,in2)
%ENERGY_TWOLINKARM
%    E = ENERGY_TWOLINKARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    23-Oct-2013 01:04:35

I1 = in2(4,:);
I2 = in2(5,:);
dth1 = in1(2,:);
dth2 = in1(4,:);
l = in2(1,:);
m1 = in2(2,:);
m2 = in2(3,:);
th1 = in1(1,:);
th2 = in1(3,:);
t5 = cos(th1);
t2 = dth2.*cos(th2).*(1.0./2.0)+dth1.*l.*t5;
t6 = sin(th1);
t3 = dth2.*sin(th2).*(1.0./2.0)+dth1.*l.*t6;
t4 = dth1.^2;
E = I1.*t4.*(1.0./2.0)+I2.*dth2.^2.*(1.0./2.0)+m1.*(t4.*t5.^2.*(1.0./4.0)+t4.*t6.^2.*(1.0./4.0)).*(1.0./2.0)+m2.*(t2.^2+t3.^2).*(1.0./2.0);
